
from database import db_conn
from fastapi import APIRouter, Depends, HTTPException, status
from models.all import (City, Facility, Permission, Role, RolePermission, User,
                        UserRole)
from sqlalchemy.orm import Session

get_db = db_conn.get_db
router = APIRouter(tags=["db_init"])


@router.post("/init_database")
def init_database(db: Session = Depends(get_db)):
    
    permission = Permission(name="register", description="", key="register")
    db.add(permission)
    permission = Permission(name="login", description="", key="login")
    db.add(permission)

    
    permission = Permission(name="create_role", description="", key="create_role")
    db.add(permission)
    permission = Permission(name="update_user_role", description="", key="update_user_role")
    db.add(permission)
    permission = Permission(name="get_role", description="", key="get_role")
    db.add(permission)
    permission = Permission(name="get_users_roles", description="", key="get_users_roles")
    db.add(permission)
    permission = Permission(name="get_all_roles", description="", key="get_all_roles")
    db.add(permission)
    permission = Permission(name="update_role", description="", key="update_role")
    db.add(permission)
    permission = Permission(name="delete_role", description="", key="delete_role")
    db.add(permission)
    permission = Permission(name="delete_user_role", description="", key="delete_user_role")
    db.add(permission)
    
    permission = Permission(name="create_rank", description="", key="create_rank")
    db.add(permission)
    permission = Permission(name="get_rank", description="", key="get_rank")
    db.add(permission)
    permission = Permission(name="get_all_ranks", description="", key="get_all_ranks")
    db.add(permission)
    permission = Permission(name="update_rank", description="", key="update_rank")
    db.add(permission)
    permission = Permission(name="delete_rank", description="", key="delete_rank")
    db.add(permission)
    
    permission = Permission(name="create_permission", description="", key="create_permission")
    db.add(permission)
    permission = Permission(name="update_permission_role", description="", key="update_permission_role")
    db.add(permission)
    permission = Permission(name="get_permission", description="", key="get_permission")
    db.add(permission)
    permission = Permission(name="get_permission_roles", description="", key="get_permission_roles")
    db.add(permission)
    permission = Permission(name="get_all_permissions", description="", key="get_all_permissions")
    db.add(permission)
    permission = Permission(name="update_permissions", description="", key="update_permissions")
    db.add(permission)
    permission = Permission(name="delete_permission", description="", key="delete_permission")
    db.add(permission)
    permission = Permission(name="delete_permission_role", description="", key="delete_permission_role")
    db.add(permission)  
    
    permission = Permission(name="create_city", description="", key="create_city")
    db.add(permission)
    permission = Permission(name="get_city", description="", key="get_city")
    db.add(permission)
    permission = Permission(name="get_all_cities", description="", key="get_all_cities")
    db.add(permission)
    permission = Permission(name="update_city", description="", key="update_city")
    db.add(permission)
    permission = Permission(name="delete_city", description="", key="delete_city")

    
    permission = Permission(name="create_facility", description="", key="create_facility")
    db.add(permission)
    permission = Permission(name="get_facility", description="", key="get_facility")
    db.add(permission)
    permission = Permission(name="get_all_facilities", description="", key="get_all_facilities")
    db.add(permission)
    permission = Permission(name="update_facility", description="", key="update_facility")
    db.add(permission)
    permission = Permission(name="delete_facility", description="", key="delete_facility")
    db.add(permission)
    permission = Permission(name="add_facility_like", description="", key="add_facility_like")
    db.add(permission)
    
    permission = Permission(name="create_product", description="", key="create_product")
    db.add(permission)
    permission = Permission(name="get_product", description="", key="get_product")
    db.add(permission)
    permission = Permission(name="get_all_products", description="", key="get_all_products")
    db.add(permission)
    permission = Permission(name="update_product", description="", key="update_product")
    db.add(permission)
    permission = Permission(name="delete_product", description="", key="delete_product")
    db.add(permission)
    
    permission = Permission(name="create_purchase", description="", key="create_purchase")
    db.add(permission)
    permission = Permission(name="get_purchase", description="", key="get_purchase")
    db.add(permission)
    permission = Permission(name="get_all_purchases", description="", key="get_all_purchases")
    db.add(permission)
    permission = Permission(name="update_purchase", description="", key="update_purchase")
    db.add(permission)
    permission = Permission(name="delete_purchase", description="", key="delete_purchase")
    db.add(permission)
    
    permission = Permission(name="get_facility_media", description="", key="get_facility_media")
    db.add(permission)
    permission = Permission(name="get_product_media", description="", key="get_product_media")
    db.add(permission)
    permission = Permission(name="get_all_media", description="", key="get_all_media")
    db.add(permission)
    permission = Permission(name="delete_media", description="", key="delete_media")
    db.add(permission)

    
    permission = Permission(name="create_banner", description="", key="create_banner")
    db.add(permission)
    permission = Permission(name="get_banner", description="", key="get_banner")
    db.add(permission)
    permission = Permission(name="get_all_banners", description="", key="get_all_banners")
    db.add(permission)
    permission = Permission(name="update_banner", description="", key="update_banner")
    db.add(permission)
    permission = Permission(name="delete_banner", description="", key="delete_banner")
    db.add(permission)

    permission = Permission(name="create_package", description="", key="create_package")
    db.add(permission)
    permission = Permission(name="get_package", description="", key="get_package")
    db.add(permission)
    permission = Permission(name="get_all_packages", description="", key="get_all_packages")
    db.add(permission)
    permission = Permission(name="update_package", description="", key="update_package")
    db.add(permission)
    permission = Permission(name="delete_package", description="", key="delete_package")
    db.add(permission)

    permission = Permission(name="create_subscription", description="", key="create_subscription")
    db.add(permission)
    permission = Permission(name="get_subscription", description="", key="get_subscription")
    db.add(permission)
    permission = Permission(name="get_all_subscriptions", description="", key="get_all_subscriptions")
    db.add(permission)
    permission = Permission(name="update_subscription", description="", key="update_subscription")
    db.add(permission)
    permission = Permission(name="delete_subscription", description="", key="delete_subscription")
    db.add(permission)

    permission = Permission(name="create_story", description="", key="create_story")
    db.add(permission)
    permission = Permission(name="get_story", description="", key="get_story")
    db.add(permission)
    permission = Permission(name="get_all_stories", description="", key="get_all_stories")
    db.add(permission)
    permission = Permission(name="get_all_facility_stories", description="", key="get_all_facility_stories")
    db.add(permission)
    permission = Permission(name="update_story", description="", key="update_story")
    db.add(permission)
    permission = Permission(name="delete_story", description="", key="delete_story")
    db.add(permission)

    permission = Permission(name="create_card", description="", key="create_card")
    db.add(permission)
    permission = Permission(name="get_card", description="", key="get_card")
    db.add(permission)
    permission = Permission(name="get_all_cards", description="", key="get_all_cards")
    db.add(permission)
    permission = Permission(name="get_all_facility_cards", description="", key="get_all_facility_cards")
    db.add(permission)
    permission = Permission(name="update_card", description="", key="update_card")
    db.add(permission)
    permission = Permission(name="delete_card", description="", key="delete_card")
    db.add(permission)

    permission = Permission(name="get_category",description="", key="get_category")
    db.add(permission)
    permission = Permission(name="get_all_categories",description="", key="get_all_categories")
    db.add(permission)
    permission = Permission(name="update_category",description="", key="update_category")
    db.add(permission)
    permission = Permission(name="delete_category",description="", key="delete_category")
    db.add(permission)
    permission = Permission(name="get_category",description="", key="get_category")
    db.add(permission)

    permission = Permission(name="create_setting",description="", key="create_setting")
    db.add(permission)
    permission = Permission(name="get_setting",description="", key="get_setting")
    db.add(permission)
    permission = Permission(name="get_all_settings",description="", key="get_all_settings")
    db.add(permission)
    permission = Permission(name="update_setting",description="", key="update_setting")
    db.add(permission)
    permission = Permission(name="delete_setting",description="", key="delete_setting")
    db.add(permission)

    permission = Permission(name="create_message",description="", key="create_message")
    db.add(permission)
    permission = Permission(name="get_message",description="", key="get_message")
    db.add(permission)
    permission = Permission(name="get_all_messages",description="", key="get_all_messages")
    db.add(permission)
    permission = Permission(name="update_message",description="", key="update_message")
    db.add(permission)
    permission = Permission(name="delete_message",description="", key="delete_message")
    db.add(permission)

    permission = Permission(name="get_comment",description="", key="get_comment")
    db.add(permission)
    permission = Permission(name="get_all_comments",description="", key="get_all_comments")
    db.add(permission)
    permission = Permission(name="update_comment",description="", key="update_comment")
    db.add(permission)
    permission = Permission(name="delete_comment",description="", key="delete_comment")
    db.add(permission)
    super_user = User(
        username='obada', password=pwd_cxt.hash('123'), email='obadatahboub20@gmail.com'
    )
    db.add(super_user)
    
    for i in range(15):
        user = User(
        username=f'{i}', password=pwd_cxt.hash('123'), email=f'obada{i}tahboub@gmail.com')
        db.add(user)
        city = City(
        name=f'{i}')
        db.add(city)
        db.commit()

        db.refresh(city)
        db.refresh(user)

        facility = Facility(
        name=f'{i}', email=f'obada{i}tahboub@gmail.com', user_id=user.id, city_id=city.id)
        db.add(facility)

    super_role = Role(name= "SUPERUSER", description='SUPERUSER')
    user_role = Role(name= "USER", description='USER')
    facility_role = Role(name= "FACILITY", description='FACILITY')
    db.add(super_role)
    db.add(facility_role)
    db.add(user_role)

    db.commit()

    db.refresh(super_user)
    db.refresh(super_role)

    new_user_role = UserRole(role_id=super_role.id, user_id=super_user.id)
    db.add(new_user_role)
    db.commit()

    return {"done":"done"}
    