"""init

Revision ID: 6ad1758c65ea
Revises: 
Create Date: 2021-12-01 19:23:21.229598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad1758c65ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Permission', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint('unique_permission_role', 'role_permission', type_='unique')
    op.drop_column('Permission', 'description')
    op.create_table('association',
    sa.Column('Role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('User_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Role_id'], ['Role.id'], name='association_Role_id_fkey'),
    sa.ForeignKeyConstraint(['User_id'], ['User.id'], name='association_User_id_fkey')
    )
    # ### end Alembic commands ###
