"""inittt

Revision ID: 9164c164c2e3
Revises: 24c629282361
Create Date: 2021-12-01 20:28:27.928245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9164c164c2e3'
down_revision = '24c629282361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('City', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint('unique_permission_role', 'role_permission', type_='unique')
    # ### end Alembic commands ###
